### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by k3ithos**
Fixes some little errors - checkout the commits for more info.

### CODE REVIEW

**Comment by MichaelM04** [comment]
I still get this when I try loading plugin 
:38] [INFO]: Enabling HungerGames v1.2
[10:46:38] [WARNING]: A plugin attempted to register a deprecated CallbackTask (Callback#HG\Main::gameTimber)
[10:46:38] [NOTICE]: InvalidArgumentException: "Argument 1 passed to pocketmine\scheduler\CallbackTask::__construct() must be callable, array given, called in phar:///home/tcagame_svc1232/AJM/1232/plugins/hunger games.phar/src/HG/Main.php on line 55 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/scheduler/CallbackTask" at line 45
[10:46:38] [INFO]: Disabling HungerGames v1.2

**Comment by ZhenMC** [comment]
is this is working?

**Comment by ZhenMC** [comment]
Nice plugin btw

**Comment by MichaelM04** [comment]
I see that now lol so many things wrong with this code

**Comment by MichaelM04** [comment]
Easily fixed just forgot a semicolon on line 646

**Comment by ZhenMC** [comment]
This is Cool Plugin ... Sorry i dont know how to code hoping that MinecrafterPH will finish the Pligin :)

**Comment by ZhenMC** [comment]
plugin*.. Someone Help me How to fix the Crash?

**Comment by MichaelM04** [comment]
Nobody Wants Too I Don't Know How To Fix The Error On Line 45 And 55 =/

**Comment by Taki21** [comment]
I will check line 55

**Pull request merged**
